additional changes to fpsync

diff --git a/kfpsync b/kfpsync
--- a/kfpsync
+++ b/kfpsync
@@ -52,7 +52,9 @@ OPT_DIRSONLY=""
 # SSH workers (execute jobs locally if not defined, -w)
 OPT_WRKRS=""
 # Kubernetes worker enabled
-OPT_K8S_IMAGE=""
+OPT_K8S_ENABLED=""
+OPT_K8S_IMAGE="fra.ocir.io/fsssolutions/rclone-rsync:latest"
+OPT_K8S_PVC="lustre-pvc"
 # Fpart shared dir (must be shared amongst all workers, -d)
 OPT_FPSHDIR=""
 # Temporary dir (local, used for queue management, -t)
@@ -322,6 +324,7 @@ tool_get_fpart_mode_opts () {
 tool_init_fpart_job_command () {
     case "$1" in
     "rsync")
+        # Remove --from0 to avoid null terminated file names. Compatibility with rclone
         FPART_JOBCOMMAND="/bin/sh -c '${SUDO} ${TOOL_BIN} ${OPT_TOOL} \
             ${TOOL_MODEOPTS} --files-from=\\\"\${FPART_PARTFILENAME}\\\" \
             \\\"${OPT_SRCDIR}/\\\" \
@@ -330,20 +333,22 @@ tool_init_fpart_job_command () {
             2>\"${FPART_LOGDIR}/\${FPART_PARTNUMBER}.stderr\""
         ;;
     "rclone")
-	rclone_dst=$(echo ${OPT_DSTURL} |cut -f1 -d:)
-	rclone_src=$(echo ${OPT_SRCDIR} | grep ":")
-	[ -n "${rclone_src}" ] && end_die "rclone is not supported from source ${rclone_src}"
-	[ "${rclone_dst}" = "${OPT_DSTURL}" ] && end_die "rclone is not supported to destination ${rclone_dst}"
+        # Make sure the rclone configuration file exist for the destination.
+        rclone_dst=$(echo ${OPT_DSTURL} |cut -f1 -d:)
+        rclone_src=$(echo ${OPT_SRCDIR} | grep ":")
+        [ -n "${rclone_src}" ] && end_die "rclone is not supported from source ${rclone_src}"
+        [ "${rclone_dst}" = "${OPT_DSTURL}" ] && end_die "rclone is not supported to destination ${rclone_dst}"
         rclone_config="$HOME/.config/rclone/rclone.conf"
         if [ ! -f "$rclone_config" ]
         then
-                    end_die "rclone configuratin file $rclone_config is missing"
+            end_die "rclone configuratin file $rclone_config is missing"
         fi
-	if ! grep "\[ *$rclone_dst *\]" $rclone_config
+        if ! grep "\[ *$rclone_dst *\]" $rclone_config >/dev/null 2>&1
         then
             end_die "$rclone_config file is missing source anchor $rclone_dst"
         fi
-	BASE64_RCLONE_CONFIG=$(base64 -w 0 $rclone_config)
+        # If the file exists, have the base64 of the file storage in the variable for k8s jobs
+        BASE64_RCLONE_CONFIG=$(base64 -w 0 $rclone_config)
         # With rclone, use the / as the source because the FPART partition file contains absolute paths.
         FPART_JOBCOMMAND="/bin/sh -c '${SUDO} ${TOOL_BIN} ${OPT_TOOL} \
             ${TOOL_MODEOPTS} --files-from=\\\"\${FPART_PARTFILENAME}\\\" copy \
@@ -400,21 +405,25 @@ tool_uses_forbidden_option () {
 parse_opts () {
     local opt OPTARG OPTIND
 
-    while getopts "m:n:f:s:EKw:d:t:M:plr:Ra:D:o:O:Svh" opt
+    while getopts "m:n:f:s:EKw:k:d:t:M:plr:Ra:D:o:O:Svh" opt
     do
         case "${opt}" in
         "K")
+            # Add options for k8s support
+            OPT_K8S_ENABLED="True"
             OPT_K8S_IMAGE="fra.ocir.io/fsssolutions/rclone-rsync:latest"
-            kubectl version >/dev/null 2>&1
-            if [ "$?" -ne "0" ]
+            OPT_K8S_PVC="lustre-pvc"
+            ;;
+        "k")
+            # k8s option with values
+            k8s_details=${OPTARG}
+            OPT_K8S_IMAGE=$(echo "${k8s_details}" | cut -f1 -d,)
+            OPT_K8S_PVC=$(echo "${k8s_details}" | cut -f2 -d,)
+            if [ -z "${OPT_K8S_PVC}" ] || [ -z "${OPT_K8S_IMAGE}" ] 
             then
-                end_die "kubectl is not working"
+                end_die "k8s value should be <image_url>,<pvc_name> Example: -k fra.ocir.io/fsssolutions/rclone-rsync:latest,lustre-pvc"
             fi
-            cnt=$(kubectl get nodes --no-headers 2>/dev/null| wc -l)
-            if [ "$cnt" -lt "1" ]
-            then
-                end_die "There are not enough worker nodes available."
-	    fi
+            OPT_K8S_ENABLED="True"
             ;;
         "m")
             if tool_is_supported "${OPTARG}"
@@ -550,6 +559,20 @@ parse_opts () {
     done
     shift $((${OPTIND} - 1))
 
+    if [ -n "${OPT_K8S_ENABLED}" ]
+    then
+        [ -n "${OPT_WRKRS}" ] && end_die "Both K8s and workers can not be done at the same time"
+        kubectl version >/dev/null 2>&1
+        if [ "$?" -ne "0" ]
+        then
+            end_die "kubectl is not working"
+        fi
+        cnt=$(kubectl get nodes --no-headers 2>/dev/null| wc -l)
+        if [ "$cnt" -lt "1" ]
+        then
+            end_die "There are not enough worker nodes available."
+        fi
+    fi
     # Validate OPT_FPSHDIR (shared directory)
     if [ -z "${OPT_WRKRS}" ]
     then
@@ -604,7 +627,7 @@ parse_opts () {
             OPT_SRCDIR="$1"
         else
             usage
-            end_die "Please supply an absolute path for src_dir/ :$1"
+            end_die "Please supply an absolute path for src_dir/"
         fi
         # Check dst_url, must be either an absolute path or a URL
         if is_abs_path "$2" || is_remote_path "$2"
@@ -686,39 +709,8 @@ work_list_refresh () {
     local _WORK_NUM=0
     for _JOB in ${WORK_LIST}
     do
-	job_name=$(echo ${_JOB} | cut -f1 -d:)
-	job_running="True"
-        if [ -n "${OPT_K8S_IMAGE}" ]	
-	then
-	    job_status=$(kubectl describe job $job_name | grep "Pods Statuses:" 2>/dev/null)
-	    if [ -z "$job_status" ]
-            then
-                echo_log "1" "<= [QMGR] ERROR: $job_name didn't start"
-                job_running="False"
-	    elif echo "$job_status" | grep  "/ 1 Succeeded /" >/dev/null
-            then
-                echo_log "1" "<= [QMGR] k8s job $job_name complete"
-                job_running="False"
-	    elif echo "$job_status" | grep -v "/ 0 Failed" >/dev/null
-            then
-                echo_log "1" "<= [QMGR] ERROR: one of the pods for $job_name failed"
-		job_running="False"
-            fi
-	    if [ "$job_running" = "False" ]
-	    then
-                kubectl delete job $job_name >/dev/null 2>&1
-                echo_log "1" "<= [QMGR] Deleting k8s job $job_name"
-	    fi
-	else
-            # If the process is still alive, keep it
-            if ps "$job_name" 1>/dev/null 2>&1
-            then
-                job_running="True"
-            else
-                job_running="False"
-            fi
-	fi
-	if [ "$job_running" = "True" ]
+        # If the process is still alive, keep it
+        if ps "$(echo ${_JOB} | cut -d ':' -f 1)" 1>/dev/null 2>&1
         then
             _WORK_LIST="${_WORK_LIST} ${_JOB}"
             _WORK_NUM="$((${_WORK_NUM} + 1))"
@@ -822,29 +814,27 @@ sigint_handler () {
         [ ${OPT_VERBOSE} -ge 1 ] && siginfo_handler
         # Exit program
         end_die
+    else
+        [ -n "${JOBLOOP_PID}" ] && kill "${JOBLOOP_PID}"
     fi
 }
 
 # Handle subsequent ^C from within job_queue_loop(): kill sync processes
 # to fast-unlock the main process (waiting for child processes to exit)
 job_queue_loop_sigint_handler () {
-    SIGINT_COUNT="$((${SIGINT_COUNT} + 1))"
-    if [ ${SIGINT_COUNT} -eq 2 ]
-    then
-        echo_log "1" "===> Interrupted again, killing remaining jobs"
-        for _JOB in ${WORK_LIST}
-        do
-            job_name=$(echo ${_JOB} | cut -f1 -d:)
-            if [ -n "${OPT_K8S_IMAGE}" ]
-            then
-                kubectl delete job $job_name
-            else
-                kill "$job_name" 1>/dev/null 2>&1
-            fi
-        done
-        # Wait for child processes to exit and let parent process end_die()
-        wait
-    fi
+    echo_log "1" "===> ERROR: job queue monitor interrupted"
+    for _JOB in ${WORK_LIST}
+    do
+        kill "$(echo ${_JOB} | cut -d ':' -f 1)" 1>/dev/null 2>&1
+        if [ -n "${OPT_K8S_ENABLED}" ]
+        then
+            job_name=$(echo ${_JOB} | cut -f3 -d:)
+            kubectl delete job $job_name >/dev/null 2>&1
+            echo_log "1" "===> Deleted k8s job $job_name"
+        fi
+    done
+    # Wait for child processes to exit and let parent process end_die()
+    wait
 }
 
 # Handle ^T: print info about queue status
@@ -871,6 +861,7 @@ siginfo_handler () {
         _run_time_remaining="$(( (${_run_elapsed_time} * ${_jobs_remaining}) / ${_run_jobs_done} ))"
     fi
 
+    local _ts=$(date)
     echo "${_ts} <===   Parts done: ${_jobs_done}/${_jobs_total} (${_jobs_percent}%), remaining: ${_jobs_remaining}"
     echo "${_ts} <=== Time elapsed: ${_run_elapsed_time}s, remaining: ~${_run_time_remaining}s (~${_run_time_per_job}s/job)"
 }
@@ -899,12 +890,72 @@ job_queue_next () {
     fi
 }
 
+# Start the k8s job and wait until completion or failure
+start_k8s_job () {
+    job_id=$1
+    k8s_job_name=$2
+    k8s_spec_file="/tmp/fpsync/${k8s_job_name}.yml"
+    echo_log "1" "===> Using kubectl to start job $k8s_job_name with $k8s_spec_file"
+cat >$k8s_spec_file <<EOF
+apiVersion: batch/v1
+kind: Job
+metadata:
+    name: ${k8s_job_name}
+spec:
+    template:
+        spec:
+            containers:
+            - name: ${k8s_job_name}
+              image: ${OPT_K8S_IMAGE}
+              env:
+              - name: FPART_JOBCOMMAND
+                value: $(cat ${JOBS_WORKDIR}/${job_id})
+              - name: BASE64_RCLONE_CONFIG
+                value: "${BASE64_RCLONE_CONFIG}"
+              volumeMounts:
+              - name: lustre-volume
+                mountPath: "/$(echo ${OPT_SRCDIR} | cut -f2 -d/)"
+            restartPolicy: Never
+            volumes:
+            - name: lustre-volume
+              persistentVolumeClaim:
+                claimName: ${OPT_K8S_PVC}
+EOF
+    kubectl create -f  $k8s_spec_file >/dev/null 2>&1
+    while true
+    do
+        job_running=True
+        sleep 1
+        job_status=$(kubectl describe job $k8s_job_name | grep "Pods Statuses:" 2>/dev/null)
+        if [ -z "$job_status" ]
+        then
+            echo_log "1" "<= [QMGR] ERROR: $k8s_job_name didn't start"
+            job_running="False"
+        elif echo "$job_status" | grep  "/ 1 Succeeded /" >/dev/null
+        then
+            echo_log "1" "<= [QMGR] k8s job $k8s_job_name complete"
+            job_running="False"
+        elif echo "$job_status" | grep -v "/ 0 Failed" >/dev/null
+        then
+            echo_log "1" "<= [QMGR] ERROR: one of the pods for $k8s_job_name failed"
+            job_running="False"
+        fi
+        if [ "$job_running" = "False" ]
+        then
+            kubectl delete job $k8s_job_name >/dev/null 2>&1
+            echo_log "1" "<= [QMGR] Deleting k8s job $k8s_job_name"
+            break
+        fi
+    done
+}
+
 # Main jobs' loop: pick up jobs within the queue directory and start them
 job_queue_loop () {
-    echo_log "2" "===> [QMGR] Starting queue manager"
+    echo_log "1" "===> [QMGR] Starting queue manager"
 
     # Trap SIGINT
     trap 'job_queue_loop_sigint_handler' 2
+    trap 'job_queue_loop_sigint_handler' 15
     # Ignore SIGINFO from within loop, handled by the parent (master) process
     trap '' 29
 
@@ -921,42 +972,12 @@ job_queue_loop () {
             then
                 if [ -z "${OPT_WRKRS}" ]
                 then
-                    echo_log "2" "=> [QMGR] Starting job ${JOBS_WORKDIR}/${_NEXT} (local)"
-		    if [ -n "${OPT_K8S_IMAGE}" ]
+                    echo_log "1" "=> [QMGR] Starting job ${JOBS_WORKDIR}/${_NEXT} (local)"
+		    if [ -n "${OPT_K8S_ENABLED}" ]
                     then
-			k8s_job_name="${OPT_TOOL_NAME}-$(basename ${JOBS_WORKDIR})-${_NEXT}"
-#			k8s_spec_file="$(dirname ${FPART_LOGFILE})/${k8s_job_name}.yml"
-                        k8s_spec_file="/tmp/fpsync/${k8s_job_name}.yml"
-                        echo_log "1" "===> Using kubectl to start job $k8s_job_name with $k8s_spec_file"
-
-cat >$k8s_spec_file <<EOF
-apiVersion: batch/v1
-kind: Job
-metadata:
-    name: ${k8s_job_name}
-spec:
-    template:
-        spec:
-            containers:
-            - name: ${k8s_job_name}
-              image: ${OPT_K8S_IMAGE}
-              env:
-              - name: FPART_JOBCOMMAND
-                value: $(cat ${JOBS_WORKDIR}/${_NEXT})
-              - name: BASE64_RCLONE_CONFIG
-                value: "${BASE64_RCLONE_CONFIG}"
-              volumeMounts:
-              - name: lustre-volume
-                mountPath: "/$(echo ${OPT_SRCDIR} | cut -f2 -d/)"
-            restartPolicy: Never
-            volumes:
-            - name: lustre-volume
-              persistentVolumeClaim:
-                claimName: lustre-pvc
-EOF
-                        out=$(kubectl create -f  $k8s_spec_file 2>&1)
-                        echo_log "1" "=> $out"
-                        work_list_push "${k8s_job_name}:k8s"
+                        k8s_job_name="${OPT_TOOL_NAME}-$(basename ${JOBS_WORKDIR})-${_NEXT}"
+                        start_k8s_job "${_NEXT}" "${k8s_job_name}" &
+                        work_list_push "$!:${_NEXT}:${k8s_job_name}"
 	            else
                         /bin/sh "${JOBS_WORKDIR}/${_NEXT}" &
                         work_list_push "$!:${_NEXT}:local"
@@ -964,7 +985,7 @@ EOF
                 else
                     local _NEXT_HOST="$(work_list_pick_next_free_worker)"
                     work_list_trunc_next_free_worker
-                    echo_log "2" "=> [QMGR] Starting job ${JOBS_WORKDIR}/${_NEXT} -> ${_NEXT_HOST}"
+                    echo_log "1" "=> [QMGR] Starting job ${JOBS_WORKDIR}/${_NEXT} -> ${_NEXT_HOST}"
                     "${SSH_BIN}" "${_NEXT_HOST}" '/bin/sh -s' \
                         < "${JOBS_WORKDIR}/${_NEXT}" &
                     work_list_push "$!:${_NEXT}:${_NEXT_HOST}"
@@ -977,12 +998,14 @@ EOF
 
     if [ "${_NEXT}" = "fp_done" ]
     then
-        echo_log "2" "<=== [QMGR] Done submitting jobs. Waiting for them to finish."
+        echo_log "1" "<=== [QMGR] Done submitting jobs. Waiting for them to finish."
     else
-        echo_log "2" "<=== [QMGR] Stopped. Waiting for jobs to finish."
+        echo_log "1" "<=== [QMGR] Stopped. Waiting for jobs to finish."
     fi
     wait
-    echo_log "2" "<=== [QMGR] Queue processed"
+    # Call work list refresh here to take care of the last process that is running. just a clean approach.
+    work_list_refresh
+    echo_log "1" "<=== [QMGR] Queue processed"
 
     # Set the 'sl_done' (sync done) flag to let the master process go
     job_queue_sl_done
@@ -1126,6 +1149,7 @@ FPART_POSTHOOK="echo \"${FPART_JOBCOMMAND}\" > \
 ## End of options' post-processing section, let's start for real now !
 
 SIGINT_COUNT="0"    # ^C counter
+JOBLOOP_PID=""      # pid for job loop
 
 WORK_NUM=0          # Current number of running processes
 WORK_LIST=""        # Work PID:PART:WORKER list
@@ -1237,7 +1261,7 @@ fi
 # presence (this also allows checking SSH connectivity to each declared host)
 if [ -n "${OPT_WRKRS}" ]
 then
-    echo_log "2" "=====> Validating requirements on SSH nodes..."
+    echo_log "1" "=====> Validating requirements on SSH nodes..."
 
     _FIRST_HOST="$(echo ${OPT_WRKRS} | awk '{print $1}')"
     for _host in ${OPT_WRKRS}
@@ -1278,7 +1302,7 @@ then
         "${SSH_BIN}" "${_host}" "/bin/sh -c '[ -x \"${TOOL_BIN}\" ]'" || \
             end_die "Tool ${OPT_TOOL_NAME} not useable on target ${_host}: ${TOOL_BIN} not found"
 
-        echo_log "2" "<=== ${_host}: OK"
+        echo_log "1" "<=== ${_host}: OK"
     done
 
     # Remove witness file
@@ -1304,21 +1328,21 @@ fi
 work_list_free_workers_init
 
 # Let's rock !
-echo_log "2" "=====> [$$] Syncing ${OPT_SRCDIR} => ${OPT_DSTURL}"
+echo_log "1" "=====> [$$] Syncing ${OPT_SRCDIR} => ${OPT_DSTURL}"
 echo_log "1" "===> Run ID: ${FPART_RUNID}$([ -n "${OPT_RUNID}" ] && echo ' (resumed)')"
-echo_log "2" "===> Start time: $(date)"
-echo_log "2" "===> Concurrent sync jobs: ${OPT_JOBS}"
-echo_log "2" "===> Workers: $(echo "${OPT_WRKRS}" | sed -E -e 's/^[[:space:]]+//' -e 's/[[:space:]]+/ /g')$([ -z "${OPT_WRKRS}" ] && echo 'local')"
-echo_log "2" "===> Shared dir: ${OPT_FPSHDIR}"
-echo_log "2" "===> Temp dir: ${OPT_TMPDIR}"
-echo_log "2" "===> Tool name: \"${OPT_TOOL_NAME}\""
+echo_log "1" "===> Start time: $(date)"
+echo_log "1" "===> Concurrent sync jobs: ${OPT_JOBS}"
+echo_log "1" "===> Workers: $(echo "${OPT_WRKRS}" | sed -E -e 's/^[[:space:]]+//' -e 's/[[:space:]]+/ /g')$([ -z "${OPT_WRKRS}" ] && echo 'local')"
+echo_log "1" "===> Shared dir: ${OPT_FPSHDIR}"
+echo_log "1" "===> Temp dir: ${OPT_TMPDIR}"
+echo_log "1" "===> Tool name: \"${OPT_TOOL_NAME}\""
 # The following options are ignored when resuming
 if [ -z "${OPT_RUNID}" ]
 then
-    echo_log "2" "===> Tool options: \"${OPT_TOOL}\""
-    echo_log "2" "===> Fpart options: \"${OPT_FPART}\""
-    echo_log "2" "===> Max files or directories per sync job: ${OPT_FPMAXPARTFILES}"
-    echo_log "2" "===> Max bytes per sync job: ${OPT_FPMAXPARTSIZE}"
+    echo_log "1" "===> Tool options: \"${OPT_TOOL}\""
+    echo_log "1" "===> Fpart options: \"${OPT_FPART}\""
+    echo_log "1" "===> Max files or directories per sync job: ${OPT_FPMAXPARTFILES}"
+    echo_log "1" "===> Max bytes per sync job: ${OPT_FPMAXPARTSIZE}"
 fi
 
 # Record run information
@@ -1334,8 +1358,9 @@ then
     # Set SIGINT and SIGINFO traps and start job_queue_loop
     trap 'sigint_handler' 2
     trap 'siginfo_handler' 29
-    echo_log "2" "===> Use ^C to abort, ^T (SIGINFO) to display status"
+    echo_log "1" "===> Use ^C to abort, ^T (SIGINFO) to display status"
     job_queue_loop&
+    JOBLOOP_PID=$!
 fi
 
 # When not resuming a previous run, start fpart
@@ -1367,6 +1392,7 @@ then
 
         # Start fpart from src_dir/ directory and produce jobs within
         # ${JOBS_QUEUEDIR}/
+        # Remove -0 to avoid null terminated file names. Compatibility with rclone
         cd "${WORK_DIR}" && \
             ${SUDO} "${FPART_BIN}" \
             $([ ${OPT_FPMAXPARTFILES} -gt 0 ] && printf '%s\n' "-f ${OPT_FPMAXPARTFILES}") \
@@ -1406,11 +1432,12 @@ else
     _report_subj="Fpsync run ${FPART_RUNID}"
 fi
 _report_logs=$(find "${FPART_LOGDIR}/" -name "*.stderr" ! -size 0)
+# Also include any errors in the FPART log file
 [ -z "${_report_logs}" ] && _report_logs=$(grep -l ERROR ${FPART_LOGFILE})
 _report_body=$( { [ -z "${_report_logs}" ] && echo 'Fpsync completed without error.' ;} || \
     { echo "Fpsync completed with errors, see logs:" && echo "${_report_logs}" ;} )
 echo_log "1" "<=== ${_report_body}"
-echo_log "2" "<=== End time: $(date)"
+echo_log "1" "<=== End time: $(date)"
 [ -n "${OPT_MAIL}" ] && \
     echo "${_report_body}" | ${MAIL_BIN} -s "${_report_subj}" ${OPT_MAIL}
 
